name: Continuous Integration

on:
  push:
    branches: [ feature/abc ]
  pull_request:
    branches: [ feature/abc ]

jobs:

  build:
    name: Build simple project
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project
      uses: actions/checkout@v2
    - name: Use Node.js 
      uses: actions/setup-node@v1

    - name: Compose up the docker
      run: docker-compose -f "docker-compose.yml" up -d --build

    - name: List all container
      run: docker ps

    - name: Run tests from the built image
      run: docker run survey-form-v2 sh -c "npm test" 
      
    - name: Compose down the docker
      run: docker-compose -f "docker-compose.yml" down


